# Result Analysis for Main Report

In [1]:
import pandas as pd

---

## Appendix A

### Table 1: Buy-and-Hold Benchmark Performance by Asset

In [2]:
df = pd.read_csv("result/buy_and_hold/summary_all_assets.csv")
print(df.columns)
df[["Asset", "Cumulative Return", "Annualized Return", "Annualized Volatility", "Annualized Sharpe", "Maximum Drawdown"]]

Index(['Asset', 'Strategy', 'Cumulative Return', 'Annualized Return',
       'Annualized Volatility', 'Annualized Sharpe', 'Maximum Drawdown',
       'Turnover', 'Number of Trades', 'Avg Return', 'Signal Return Std',
       'Precision', 'Recall'],
      dtype='object')

,Asset,Cumulative Return,Annualized Return,Annualized Volatility,Annualized Sharpe,Maximum Drawdown
0,BTC,0.400965,0.309545,0.457861,0.818031,-0.347615
1,ETH,0.167299,0.131712,0.711194,0.530271,-0.652824
2,XRP,2.013191,1.416302,0.951227,1.401183,-0.512126
3,SOL,-0.172253,-0.140333,0.857914,0.252300,-0.660623

### Table 2: Best Feasible Active Strategy Configurations After Transaction Costs

In [3]:
df = pd.read_csv("result/paper_tables/best_overall_configs_feasible.csv")
print(df.columns)
df = df[df["Cost Regime"] == "with_cost"]
df[["Asset", "Model", "Model Family", "Feature Set", "Strategy Mode", "Cost Regime", "Test Sharpe", "Cumulative Return", "Maximum Drawdown", "Number of Trades", "Annualized Sharpe"]]

Index(['Asset', 'Model', 'Model Family', 'Feature Set', 'Input Type',
       'Feature Type', 'Strategy Mode', 'Strategy Label', 'Cost Regime',
       'Long Threshold', 'Short Threshold', 'Threshold Feasible',
       'Validation Sharpe', 'Validation Precision', 'Validation Recall',
       'Validation Avg Return', 'Validation Trades', 'Validation Signal Ratio',
       'Test Sharpe', 'Test Precision', 'Test Recall', 'Test Avg Return',
       'Cumulative Return', 'Maximum Drawdown', 'Turnover', 'Number of Trades',
       'Annualized Sharpe', 'Model Params', 'Log Path', 'Feasibility Bucket'],
      dtype='object')

,Asset,Model,Model Family,Feature Set,Strategy Mode,Cost Regime,Test Sharpe,Cumulative Return,Maximum Drawdown,Number of Trades,Annualized Sharpe
1,BTC,GRU,ML,candle_extended,long_only,with_cost,0.039497,0.014295,-0.169610,546.0,0.153603
3,BTC,Logistic Regression,ML,ohlc_extended,long_short,with_cost,-0.017681,-0.169962,-0.191816,788.0,-1.494822
5,BTC,Logistic Regression,ML,ohlc_extended,short_only,with_cost,-0.025688,-0.179749,-0.196624,762.0,-1.730444
7,ETH,GRU,ML,ohlc_extended,long_only,with_cost,-0.010586,-0.009783,-0.013672,50.0,-0.485698
9,ETH,Logistic Regression,ML,candle_extended,long_short,with_cost,0.043337,0.025087,-0.136006,329.0,0.219026
11,ETH,Logistic Regression,ML,ohlc_raw,short_only,with_cost,-0.012376,-0.325165,-0.394073,1528.0,-1.056474
13,SOL,GRU,ML,candle_extended,long_only,with_cost,0.159148,0.176184,-0.107247,120.0,1.137860
15,SOL,GRU,ML,candle_extended,long_short,with_cost,0.199195,0.469984,-0.204527,228.0,1.791720
17,SOL,GRU,ML,ohlc_extended,short_only,with_cost,0.017333,-0.009314,-0.136910,314.0,0.049664
19,XRP,GRU,ML,candle_extended,long_only,with_cost,0.136439,0.273136,-0.123370,210.0,1.139927
21,XRP,Logistic Regression,ML,ohlc_extended,long_short,with_cost,-0.013537,-0.509166,-0.616527,1824.0,-1.041452
23,XRP,Logistic Regression,ML,ohlc_extended,short_only,with_cost,-0.019984,-0.589651,-0.671322,1768.0,-1.503210

### Table 3: Average Feasible Performance by Model and Strategy Mode (With Cost)

In [4]:
df = pd.read_csv("result/paper_tables/table12_feasible_bundle.csv")
df = df[(df["Scope"] == "all_assets") & (df["Cost_Regime"] == "with_cost")]

df[["Model", "Strategy_Mode", "Test Sharpe", "Test Precision", "Test Recall", "Test Avg Return"
]]

,Model,Strategy_Mode,Test Sharpe,Test Precision,Test Recall,Test Avg Return
0,GRU,long_only,0.052970,0.588544,0.084514,8.458190e-04
1,LightGBM,long_only,0.015074,0.548146,0.072491,3.792416e-04
2,Logistic Regression,long_only,0.038226,0.558170,0.038583,5.500315e-04
3,RSI,long_only,-0.002637,0.533457,0.451698,5.569275e-07
4,SMA,long_only,0.026608,0.523912,0.058512,3.623794e-04
5,XGBoost,long_only,-0.012769,0.517558,0.173099,-9.751999e-05
12,GRU,short_only,-0.055443,0.515812,0.091304,-3.747685e-04
13,LightGBM,short_only,-0.015110,0.507488,0.110456,-2.287981e-04
14,Logistic Regression,short_only,-0.004841,0.526865,0.331520,-4.327898e-05
15,RSI,short_only,-0.012719,0.516236,0.483814,-1.216415e-04
16,SMA,short_only,-0.023375,0.484834,0.306747,-5.030647e-04
17,XGBoost,short_only,-0.024454,0.503124,0.199777,-2.064850e-04
24,GRU,long_short,0.029658,0.577249,0.094824,2.174115e-04
25,LightGBM,long_short,-0.009592,0.531893,0.089839,-1.100359e-04
26,Logistic Regression,long_short,0.007647,0.556135,0.138734,8.927192e-05
27,RSI,long_short,-0.009022,0.524681,0.463395,-9.669564e-05
28,SMA,long_short,-0.012337,0.493434,0.123191,-1.323381e-04
29,XGBoost,long_short,-0.019610,0.510700,0.192056,-2.012464e-04

### Table 4: Average Transaction Cost Drag by Model and Strategy Mode

In [5]:
df = pd.read_csv("result/paper_tables/cost_drag_summary_by_asset_model_strategy_feasible.csv")

# aggregate across assets
a6 = (
    df.groupby(["Model", "Strategy Mode"], as_index=False)
      .agg({
          "Sharpe Cost Drag": "mean",
          "Avg Return Cost Drag": "mean",
          "Cumulative Return Cost Drag": "mean"
      })
)
a6

,Model,Strategy Mode,Sharpe Cost Drag,Avg Return Cost Drag,Cumulative Return Cost Drag
0,GRU,long_only,0.024460,0.000209,0.179548
1,GRU,long_short,0.019931,0.000161,0.257989
2,GRU,short_only,0.028632,0.000179,0.236016
3,LightGBM,long_only,0.038513,0.000274,0.321102
4,LightGBM,long_short,0.029821,0.000242,0.514533
5,LightGBM,short_only,0.031328,0.000249,0.320139
6,Logistic Regression,long_only,0.030738,0.000275,0.261144
7,Logistic Regression,long_short,0.025920,0.000177,0.524344
8,Logistic Regression,short_only,0.024100,0.000150,0.495159
9,RSI,long_only,0.009495,0.000068,0.589230
10,RSI,long_short,0.007527,0.000088,0.578891
11,RSI,short_only,0.005626,0.000059,0.331985
12,SMA,long_only,0.002002,0.000017,0.030211
13,SMA,long_short,0.001209,0.000014,0.038244
14,SMA,short_only,0.000433,0.000009,0.021534
15,XGBoost,long_only,0.030239,0.000237,0.641368
16,XGBoost,long_short,0.025520,0.000256,0.975676
17,XGBoost,short_only,0.025738,0.000230,0.588234

### Table 5: Bootstrap-Based Statistical Usefulness of Best Strategies

In [6]:
df = pd.read_csv("result/stat_tests/usefulness_tests_best_overall_feasible.csv")
df = df[df["Cost Regime"] == "with_cost"]
df[["Asset", "Model", "Strategy Mode", "Mean Net Return", "p-value vs 0", "Mean Excess Return vs BuyHold", "p-value vs BuyHold"]]

,Asset,Model,Strategy Mode,Mean Net Return,p-value vs 0,Mean Excess Return vs BuyHold,p-value vs BuyHold
1,BTC,GRU,long_only,2.202891e-06,0.4403,-0.000043,0.8425
3,BTC,Logistic Regression,long_short,-1.651581e-05,0.9581,-0.000060,0.8948
5,BTC,Logistic Regression,short_only,-1.767732e-05,0.9776,-0.000061,0.8990
7,ETH,GRU,long_only,-8.864273e-07,0.7394,-0.000048,0.7441
9,ETH,Logistic Regression,long_short,3.208571e-06,0.4136,-0.000040,0.6974
11,ETH,Logistic Regression,short_only,-3.194912e-05,0.8689,-0.000075,0.7945
13,SOL,GRU,long_only,1.557209e-05,0.0878,-0.000013,0.5642
15,SOL,GRU,long_short,3.705404e-05,0.0106,0.000009,0.4647
17,SOL,GRU,short_only,1.020538e-06,0.4813,-0.000027,0.6211
19,XRP,GRU,long_only,2.406502e-05,0.0709,-0.000134,0.9233
21,XRP,Logistic Regression,long_short,-5.349166e-05,0.9091,-0.000207,0.9593
23,XRP,Logistic Regression,short_only,-7.155204e-05,0.9614,-0.000225,0.9694

---

## Appendix B

### Table 1: Sample of Feasible Strategy Configurations (With Cost)

In [7]:
df = pd.read_csv("result/paper_tables/table_detail_feasible_configs.csv")
df = df[df["Cost Regime"] == "with_cost"]
print(df.columns)
df = df.drop(columns=["Model Family", "Input Type", "Feature Type", "Threshold Feasible", "Feasibility Bucket", "Model Params"])

# sort by performance
df = df.sort_values(by="Annualized Sharpe", ascending=False)
# show top 10
df.head(10)

Index(['Asset', 'Model', 'Model Family', 'Input Type', 'Feature Type',
       'Feature Set', 'Strategy Label', 'Cost Regime', 'Threshold Feasible',
       'Feasibility Bucket', 'Validation Sharpe', 'Validation Precision',
       'Validation Recall', 'Validation Avg Return', 'Validation Trades',
       'Validation Signal Ratio', 'Test Sharpe', 'Test Precision',
       'Test Recall', 'Test Avg Return', 'Cumulative Return',
       'Maximum Drawdown', 'Turnover', 'Number of Trades', 'Annualized Sharpe',
       'Model Params'],
      dtype='object')

,Asset,Model,Feature Set,Strategy Label,Cost Regime,Validation Sharpe,Validation Precision,Validation Recall,Validation Avg Return,Validation Trades,Validation Signal Ratio,Test Sharpe,Test Precision,Test Recall,Test Avg Return,Cumulative Return,Maximum Drawdown,Turnover,Number of Trades,Annualized Sharpe
19,XRP,Logistic Regression,candle_extended,long,with_cost,-0.034557,0.608871,0.027515,-0.000495,348,0.022648,0.280029,0.659091,0.021045,0.003488,0.705594,-0.158772,318.0,318.0,2.264394
25,SOL,GRU,candle_extended,long_short,with_cost,0.180380,0.805419,0.011426,0.002610,284,0.018669,0.199195,0.625000,0.009896,0.002532,0.469984,-0.204527,228.0,228.0,1.791720
77,SOL,Logistic Regression,candle_extended,long,with_cost,0.206952,0.602094,0.062933,0.001785,838,0.052329,0.157153,0.573770,0.031441,0.001924,0.592129,-0.154548,490.0,490.0,1.663648
15,XRP,LightGBM,candle_extended,long,with_cost,0.004105,0.651685,0.010569,0.000369,136,0.008128,0.234382,0.685714,0.013062,0.004902,0.568387,-0.145782,174.0,174.0,1.662529
27,XRP,Logistic Regression,ohlc_extended,long,with_cost,-0.004145,0.616487,0.031341,0.000079,372,0.025479,0.146629,0.618375,0.031749,0.002267,0.670138,-0.189672,428.0,428.0,1.554226
153,ETH,LightGBM,candle_raw,short,with_cost,-0.000779,0.567474,0.030444,0.000006,532,0.026393,0.146954,0.531722,0.032744,0.001044,0.279370,-0.064289,504.0,504.0,1.538350
321,XRP,SMA,rule_based,long,with_cost,0.017617,0.534146,0.040088,0.000399,56,0.037611,0.072745,0.500536,0.085033,0.000970,1.124256,-0.336444,92.0,92.0,1.526516
231,BTC,GRU,ohlc_raw,long_short,with_cost,0.024219,0.755288,0.467885,0.000092,242,0.934657,0.068708,0.518373,0.035592,0.000324,0.242300,-0.070163,114.0,114.0,1.439082
33,XRP,GRU,candle_extended,long,with_cost,0.149188,0.705882,0.024096,0.002213,274,0.017114,0.136439,0.603053,0.014358,0.002286,0.273136,-0.123370,210.0,210.0,1.139927
45,SOL,GRU,candle_extended,long,with_cost,0.276592,0.660550,0.013160,0.004383,158,0.009975,0.159148,0.595506,0.009536,0.002161,0.176184,-0.107247,120.0,120.0,1.137860

### Table 2: Comparison of Strategy Performance Before and After Transaction Costs

In [8]:
df = pd.read_csv("result/paper_tables/cost_comparison_by_configuration_feasible.csv")

# keep only relevant columns
b2 = df[[
    "Asset",
    "Model",
    "Strategy Mode",
    "Test Sharpe no_cost",
    "Test Sharpe with_cost",
    "Cumulative Return no_cost",
    "Cumulative Return with_cost"
]].copy()

# compute cost impact explicitly (nice addition)
b2["Sharpe Cost Drag"] = b2["Test Sharpe no_cost"] - b2["Test Sharpe with_cost"]
b2["Return Cost Drag"] = b2["Cumulative Return no_cost"] - b2["Cumulative Return with_cost"]

# sort by largest Sharpe deterioration
b2 = b2.sort_values(by="Sharpe Cost Drag", ascending=False)
# show top 10 rows
b2 = b2.head(10)
b2

,Asset,Model,Strategy Mode,Test Sharpe no_cost,Test Sharpe with_cost,Cumulative Return no_cost,Cumulative Return with_cost,Sharpe Cost Drag,Return Cost Drag
18,BTC,LightGBM,long_only,0.194980,0.094050,0.077686,-0.001470,0.100930,0.079155
21,BTC,LightGBM,long_only,0.026888,-0.068100,0.034784,-0.196877,0.094988,0.231661
19,BTC,LightGBM,long_short,0.161201,0.072847,0.189135,-0.009401,0.088354,0.198536
60,ETH,GRU,long_only,0.075632,-0.010586,0.007699,-0.009783,0.086218,0.017483
14,BTC,LightGBM,short_only,0.095519,0.015849,0.252769,-0.133688,0.079671,0.386457
13,BTC,LightGBM,long_short,0.065511,-0.008619,0.221080,-0.226909,0.074130,0.447988
20,BTC,LightGBM,short_only,0.077563,0.007114,0.158444,-0.111510,0.070449,0.269954
5,BTC,GRU,short_only,0.076940,0.008111,1.074633,-0.402811,0.068829,1.477444
26,BTC,Logistic Regression,short_only,0.084394,0.017440,0.436525,-0.172543,0.066954,0.609068
62,ETH,GRU,short_only,-0.313806,-0.379498,-0.031640,-0.045115,0.065693,0.013476

### Table 3: Input Representation Comparison (OHLC vs Candlestick)

In [9]:
df = pd.read_csv("result/paper_tables/table10_feasible_bundle.csv")

# apply filters
b3 = df[
    (df["Scope"] == "all_assets") &
    (df["Cost_Regime"] == "with_cost")
].copy()

# select relevant columns
b3 = b3[[
    "Input Type",
    "Strategy_Mode",
    "Test Sharpe",
    "Test Precision",
    "Test Avg Return"
]]

# rename for cleaner presentation
b3 = b3.rename(columns={
    "Strategy_Mode": "Strategy Mode",
    "Test Sharpe": "Annualized Sharpe",
    "Test Avg Return": "Average Return"
})
# sort for readability
b3 = b3.sort_values(by=["Strategy Mode", "Annualized Sharpe"], ascending=[True, False])

b3

  Input Type Strategy Mode  Annualized Sharpe  Test Precision  Average Return
1       ohlc     long_only           0.025516        0.562904        0.000425
0     candle     long_only           0.019519        0.542504        0.000401
8     candle    long_short           0.004694        0.566658        0.000043
9       ohlc    long_short          -0.000642        0.521330       -0.000046
4     candle    short_only          -0.013162        0.515034       -0.000171
5       ohlc    short_only          -0.036762        0.511610       -0.000256

### Table 4: Feature Engineering Comparison (Raw vs Extended Features)

In [10]:
df = pd.read_csv("result/paper_tables/table11_feasible_bundle.csv")

# apply filters
b4 = df[
    (df["Scope"] == "all_assets") &
    (df["Cost_Regime"] == "with_cost")
].copy()

# select relevant columns
b4 = b4[[
    "Feature Type",
    "Strategy_Mode",
    "Test Sharpe",
    "Test Precision",
    "Test Avg Return"
]]

# rename for clean presentation
b4 = b4.rename(columns={
    "Strategy_Mode": "Strategy Mode",
    "Test Sharpe": "Annualized Sharpe",
    "Test Avg Return": "Average Return"
})
b4 = b4.sort_values(by=["Strategy Mode", "Annualized Sharpe"], ascending=[True, False])

b4

,Feature Type,Strategy Mode,Annualized Sharpe,Test Precision,Average Return
0,extended,long_only,0.047231,0.580818,0.000809
1,raw,long_only,-0.002390,0.523354,0.000003
8,extended,long_short,0.011195,0.576018,0.000113
9,raw,long_short,-0.007143,0.511970,-0.000115
5,raw,short_only,-0.020162,0.495822,-0.000180
4,extended,short_only,-0.029762,0.530823,-0.000247